config/routes.rb
Rails.application.routes.draw do
  resources :answers
  devise_for :users
  resources :rounds
  resources :categories
  resources :games
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :game
  has_many :answers
  validates :letter, presence: true
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: %i[ show edit update destroy ]

  # GET /rounds or /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1 or /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds or /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to round_url(@round), notice: "Round was successfully created." }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1 or /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to round_url(@round), notice: "Round was successfully updated." }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1 or /rounds/1.json
  def destroy
    @round.destroy!

    respond_to do |format|
      format.html { redirect_to rounds_url, notice: "Round was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def round_params
      params.require(:round).permit(:letter, :status, :game_id)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_with(model: round) do |form| %>
  <% if round.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
        <% round.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :letter, style: "display: block" %>
    <%= form.text_field :letter %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.text_field :game_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rounds/_round.html.erb
<div id="<%= dom_id round %>">
  <p>
    <strong>Letter:</strong>
    <%= round.letter %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= round.status %>
  </p>

  <p>
    <strong>Game:</strong>
    <%= round.game_id %>
  </p>

</div>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render "form", round: @round %>

<br>

<div>
  <%= link_to "Show this round", @round %> |
  <%= link_to "Back to rounds", rounds_path %>
</div>

app/views/rounds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rounds</h1>

<div id="rounds">
  <% @rounds.each do |round| %>
    <%= render round %>
    <p>
      <%= link_to "Show this round", round %>
    </p>
  <% end %>
</div>

<%= link_to "New round", new_round_path %>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render "form", round: @round %>

<br>

<div>
  <%= link_to "Back to rounds", rounds_path %>
</div>

app/views/rounds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @round %>

<div>
  <%= link_to "Edit this round", edit_round_path(@round) %> |
  <%= link_to "Back to rounds", rounds_path %>

  <%= button_to "Destroy this round", @round, method: :delete %>
</div>