config/routes.rb
Rails.application.routes.draw do
  resources :answers
  devise_for :users
  resources :rounds
  resources :categories
  resources :games
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "games#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :round
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_url, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:text, :score, :user_id, :round_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p>
    <strong>Text:</strong>
    <%= answer.text %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= answer.score %>
  </p>

  <p>
    <strong>User:</strong>
    <%= answer.user_id %>
  </p>

  <p>
    <strong>Round:</strong>
    <%= answer.round_id %>
  </p>

</div>

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :round_id, style: "display: block" %>
    <%= form.text_field :round_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Show this answer", @answer %> |
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Answers</h1>

<div id="answers">
  <% @answers.each do |answer| %>
    <%= render answer %>
    <p>
      <%= link_to "Show this answer", answer %>
    </p>
  <% end %>
</div>

<%= link_to "New answer", new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<div>
  <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
  <%= link_to "Back to answers", answers_path %>

  <%= button_to "Destroy this answer", @answer, method: :delete %>
</div>